2025-01-31 15:05:18,435 - Starting new HTTP connection (1): localhost:8082
2025-01-31 15:05:18,437 - GET http://localhost:8082/pingallendorsers - Request failed: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /pingallendorsers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105d1bb90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-31 15:05:19,446 - Starting new HTTP connection (1): localhost:8082
2025-01-31 15:05:19,448 - GET http://localhost:8082/gettimeoutmap - Request failed: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /gettimeoutmap (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105d2ca90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-31 15:05:20,453 - Starting new HTTP connection (1): localhost:8082
2025-01-31 15:05:20,455 - PUT http://localhost:8082/addendorsers - Request failed: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /addendorsers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105d2eb90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-31 15:05:20,459 - Output of command /Users/matheis/VSCProjects/Nimble/target/release/endorser -p9090:
2025-01-31 15:05:20,459 - stdout:
2025-01-31 15:05:20,459 - Endorser host listening on [::1]:9090
Pinged Endorser
Pinged Endorser
Pinged Endorser
Pinged Endorser
Pinged Endorser
Pinged Endorser
Pinged Endorser

2025-01-31 15:05:20,459 - stderr:
2025-01-31 15:05:20,459 - 
2025-01-31 15:05:20,459 - Output of command /Users/matheis/VSCProjects/Nimble/target/release/endorser -p9091:
2025-01-31 15:05:20,459 - stdout:
2025-01-31 15:05:20,459 - Endorser host listening on [::1]:9091

2025-01-31 15:05:20,459 - stderr:
2025-01-31 15:05:20,460 - 
2025-01-31 15:05:20,460 - Output of command /Users/matheis/VSCProjects/Nimble/target/release/coordinator -ehttp://localhost:9090 -i1:
2025-01-31 15:05:20,460 - stdout:
2025-01-31 15:05:20,460 - Coordinator starting with max_failures: 3, request_timeout: 10, min_alive_percentage: 66, quorum_size: 3
Connected to new endorsers
Desired quorum size: 3
New endorser URI: http://localhost:9090
created view ledger genesis block
read view ledger tail
appended view ledger genesis block
Endorser URIs: ["http://localhost:9090"]
Pinging all Endorsers method called from main.rs
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Started the scheduler
Running control service at [::1]:8090
Running gRPC Coordinator Service at [::1]:8080
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090
Pinging all endorsers from coordinator_state
Nonce match for endorser: http://localhost:9090

2025-01-31 15:05:20,460 - stderr:
2025-01-31 15:05:20,460 - 
2025-01-31 15:05:20,460 - Output of command /Users/matheis/VSCProjects/Nimble/target/release/endpoint_rest:
2025-01-31 15:05:20,460 - stdout:
2025-01-31 15:05:20,460 - 
2025-01-31 15:05:20,460 - stderr:
2025-01-31 15:05:20,460 - thread 'main' panicked at /Users/matheis/VSCProjects/Nimble/endpoint/src/lib.rs:268:63:
called `Result::unwrap()` on an `Err` value: FailedToReadViewLedger
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

